Repository jenkinsci/aws-global-configuration-plugin, pull requests merged in 2020-06, with the labels that each got.

#15 Do not use buildPlugin.recommendedConfigurations()
  Jenkinsfile
Labels: chore

#14 GitHub docs & Release Drafter
  .github/release-drafter.yml
  README.md
  old-changes.md
  pom.xml
Labels: documentation

#12 Update infra
  pom.xml
Labels: chore

#13 Configuration-as-code test
  pom.xml
  src/test/java/io/jenkins/plugins/aws/global_configuration/CascTest.java
  src/test/resources/io/jenkins/plugins/aws/global_configuration/configuration-as-code.yaml
Labels: tests
