Repository jenkinsci/aws-global-configuration-plugin, pull requests merged in 2023-03, with the labels that each got.

#51 Use https instead of git for SCM connection in pom
  pom.xml
Labels: developer

#52 Add more spotbugs checks
  pom.xml
Labels: chore

#56 Bump to 2.361.x
  .github/CODEOWNERS
  Jenkinsfile
  README.md
  old-changes.md
  pom.xml
  src/main/java/io/jenkins/plugins/aws/global_configuration/CredentialsAwsGlobalConfiguration.java
Labels: dependencies
